server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: credit-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/creditDB
    username: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://eureka-microservice-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true