server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: financialEvaluationMicroservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/documentDB
    username: postgres
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true