server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://userMicroservice
          predicates:
            - Path=/user/**
        - id: creditMicroservice
          uri: lb://creditMicroservice
          predicates:
            - Path=/credit/**