server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: user-microservice
          uri: lb://USERMICROSERVICE
          predicates:
            - Path=/user/**
        - id: credit-microservice
          uri: lb://credit-microservice
          predicates:
            - Path=/credit/**
        - id: document-microservice
          uri: lb://document-microservice
          predicates:
            - Path=/document/**