server:
  port: ${SERVER_PORT}

spring:
  application:
    name: user-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME} # Cambia localhost por el nombre del servicio
    username: ${DB_USER} # Usa variables inyectadas desde Secrets
    password: ${DB_PASSWORD} # Usa variables inyectadas desde Secrets
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true