server:
  port: ${SERVER_PORT}

spring:
  application:
    name: user-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://eureka-microservice-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true