server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: user-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://user-db-service:5432/userDB # Cambia localhost por el nombre del servicio
    username: ${DB_USER_USER} # Usa variables inyectadas desde Secrets
    password: ${DB_PASSWORD_USER} # Usa variables inyectadas desde Secrets
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
eureka:
  instance:
    preferIpAddress: true
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true