server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: utils-microservice

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true