apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-microservice-deployment
  labels:
    app: config-microservice-deployment
spec:
  selector:
    matchLabels:
      app: config-microservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: config-microservice-deployment
    spec:
      containers:
        - name: config-microservice
          image: mellow03/config-microservice:latest
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-microservice-service
  labels:
    app: config-microservice-service
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: config-microservice-deployment