apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-microservice-deployment
  labels:
    app: gateway-microservice-deployment
spec:
  selector:
    matchLabels:
      app: gateway-microservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-microservice-deployment
    spec:
      containers:
        - name: gateway-microservice
          image: mellow03/gateway-microservice:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice-service
  labels:
    app: gateway-microservice-service
spec:
  selector:
    app: gateway-microservice-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer