apiVersion: apps/v1
kind: Deployment
metadata:
  name: utils-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utils-microservice-deployment
  template:
    metadata:
      labels:
        app: utils-microservice-deployment
    spec:
      containers:
        - name: utils-microservice-container
          image: mellow03/utils-microservice:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://backend-config:8081
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://backend-eureka:8761
            - name: eureka.instance.preferIpAddress
              value: "true"