apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice-deployment
  template:
    metadata:
      labels:
        app: user-microservice-deployment
    spec:
      containers:
        - name: user-microservice-container
          image: mellow03/user-microservice:latest
          ports:
            - containerPort: 9090
          env:
            - name: SERVER_PORT
              value: "0"
            # Variables desde ConfigMap (no sensibles)
            - name: DB_HOST
              value: user-db-service

            - name: DB_PORT
              value: "5432"

            - name: DB_DBNAME
              value: userDB

            # Variables desde Secret (sensibles)
            - name: DB_USER
              value: postgres

            - name: DB_PASSWORD
              value: admin