apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  POSTGRES_DB_HOST: postgres
  POSTGRES_DB_USER: dbuser
  POSTGRES_DB_FINANCIAL_EVALUATION: dbfinancialevaluation
  POSTGRES_DB_CREDIT: dbcredit
  POSTGRES_DB_DOCUMENT: dbdocument