apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-deployment
  labels:
    app: user-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: user-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-db-deployment
        tier: database
    spec:
      containers:
        - name: user-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_DB
              value: userDB
---
apiVersion: v1
kind: Service
metadata:
  name: user-db-service
  labels:
    app: user-db-service
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: user-db-deployment
    tier: database
  type: LoadBalancer