server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mellowzhong/Tingeso_Lab2
          default-label: main
          search-paths: backend/config-data